name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '17 22 * * 4'  # 22:17h UTC Thursday. Slightly later than source data updates at 4pm Eastern.

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Fetch latest data
      run: |-
        python query.py

    - name: Fail on zero-size output
      run: |-
        [ -s result-Acton.csv ] || exit 2

    - name: Commit and push if it changed
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        file_pattern: 'result-*.csv'
        commit_user_name: "github-actions[bot]" # defaults to "GitHub Actions"
        commit_user_email: actions@github.com # defaults to "actions@github.com"
        commit_author: GitHub Actions [bot] <actions@github.com> # defaults to author of the commit that triggered the run
